name: Generate Snake

on:
  schedule:
    # Runs automatically every day at midnight UTC
    - cron: "0 0 * * *"
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Game from GitHub Contribution Graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to "output" branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
